---
name: Infrastructure

on:
  workflow_dispatch:
  push:
    branches: [master, main]
  workflow_run:
    workflows: ["Continuous Integration"]
    types:
      - completed

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      PRIVATE_IP: ${{ secrets.PRIVATE_IP }}
      PUBLIC_KEY: ${{ secrets.PUBLIC_KEY }}

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
    
      - name: Setup hashicorp
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.1.7"
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
      
      - name: Initialize terraform
        run: terraform init

      - name: Apply terraform
        run: terraform apply --auto-approve -var-file terraform-dev.tfvars

