---
name: Infrastructure

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Continuous Integration"]
    types:
      - completed

jobs:
  terraform-job:
    runs-on: ubuntu-latest

  steps:
    - name: Checkout source
      uses: actions/checkout@v4
      