---
name: Infrastructure

on:
  workflow_dispatch:
  push:
    branches: [master, main]
  workflow_run:
    workflows: ["Continuous Integration"]
    types:
      - completed

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
    
      - name: Setup hashicorp
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.1.7"
      
      - name: Initialize terraform
        run: terraform init

      - name: Apply terraform
        run: terraform apply --auto-approve -var-file terraform-dev.tfvars

